from dataclasses import dataclass, field
from typing import List

ROOT_DIR = 'projects'
REPO_DIR = 'project-repos'
DATASET_CSV_OUTPUT_PATH = './output/results.csv'
DATASET_DILL_OUTPUT_PATH = './output/results.dill' # better pickle
EXCLUDE_PATHS_PATH = './input/exclude_paths.txt' # made from paths for all repos

@dataclass
class ProjectConfig:
  name: str
  repo_urls: List[str]
  exclude_dirs: List[str] = field(default_factory=list)



PROJECT_CONFIGS = [
  ProjectConfig(
    name='DAI',
    repo_urls=[
      'https://github.com/makerdao/dss-cdp-manager/',
      'https://github.com/makerdao/dss-flash/',
      'https://github.com/dapphub/ds-pause',
      'https://github.com/makerdao/osm.git',
      'https://github.com/makerdao/esm/',
      'https://github.com/makerdao/median',
      'https://github.com/dapphub/ds-chief/',
      'https://github.com/dapphub/ds-spell/',
      'https://github.com/makerdao/dss.git',
      'https://github.com/makerdao/dss-proxy-actions',
      'https://github.com/makerdao/dsr-manager/',
      'https://github.com/dapphub/ds-token',
      'https://github.com/makerdao/vote-proxy/',
    ]
  ),

  ProjectConfig(
    name='AAVE',
    repo_urls=['https://github.com/aave/aave-v3-core']
  ),

  ProjectConfig(
    name='USD Tether',
    repo_urls=['https://github.com/tethercoin/USDT']
  ),

  ProjectConfig(
    name='Polygon',
    repo_urls=['https://github.com/maticnetwork/contracts']
  ),

  ProjectConfig(
    name='Chainlink',
    repo_urls=['https://github.com/smartcontractkit/chainlink']
  ),

  ProjectConfig(
    name='USDC',
    repo_urls=['https://github.com/circlefin/stablecoin-evm']
  ),

  ProjectConfig(
    name='Shiba Inu',
    repo_urls=['https://github.com/shibaswaparmy/contracts']
  ),

  ProjectConfig(
    name='Toncoin',
    repo_urls=['https://github.com/ton-blockchain/bridge-solidity']
  ),

  ProjectConfig(
    name='Uniswap',
    repo_urls=['https://github.com/Uniswap/v3-core']
  ),

  ProjectConfig(
    name='Lido DAO',
    repo_urls=['https://github.com/lidofinance/lido-dao']
  ),

  ProjectConfig(
    name='Immutable',
    repo_urls=['https://github.com/immutable/contracts']
  ),

  ProjectConfig(
    name='Mantle',
    repo_urls=['https://github.com/mantlenetworkio/mantle']
  ),

  ProjectConfig(
    name='Cronos',
    repo_urls=['https://github.com/crypto-org-chain/cronos']
  ),

  ProjectConfig(
    name='The Graph',
    repo_urls=['https://github.com/graphprotocol/contracts']
  ),

  ProjectConfig(
    name='Render',
    repo_urls=['https://github.com/rndr-network/Token-Audit']
  ),

  ProjectConfig(
    name='Synthetix',
    repo_urls=['https://github.com/Synthetixio/synthetix']
  ),

  ProjectConfig(
    name='Fantom',
    repo_urls=[
      # In general, seem to be lots of redundant/abandoned stuff
      'https://github.com/Fantom-foundation/Artion-Contracts',
      'https://github.com/Fantom-foundation/opera-sfc',
      # 'https://github.com/Fantom-foundation/qewa', # unclear what this is, excluding.
      'https://github.com/Fantom-foundation/FtmStableCoin',
      'https://github.com/Fantom-foundation/FNS-SCs', # i don't think this is used. it's an ENS clone.
      'https://github.com/Fantom-foundation/fns-contracts/tree/master', # unclear about whether this is used. I suspect no, in favor of other repos.
      'https://github.com/Fantom-foundation/Fantom-CrossChain-Bridge',
      'https://github.com/Fantom-foundation/Fantom-wFTM',
      'https://github.com/Fantom-foundation/Fantom-Contract-Validation',
      'https://github.com/Fantom-foundation/Fantom-Uniswap', # seems deployed, acc to README
      'https://github.com/Fantom-foundation/keep3r.network', # idk what this is, seems abandoned
      'https://github.com/Fantom-foundation/Fantom-Oracle-Pricefeed',
      'https://github.com/Fantom-foundation/Fantom-FLend',
      'https://github.com/Fantom-foundation/data-hashing-authentication',
      'https://github.com/Fantom-foundation/Fantom-DeFi', # possibly not used
      'https://github.com/Fantom-foundation/Fantom-Fusd'
    ]
  ),

  ProjectConfig(
    name='The Sandbox',
    repo_urls=['https://github.com/thesandboxgame/sandbox-smart-contracts']
  ),

  ProjectConfig(
    name='Axie Infinity',
    repo_urls=[
      'https://github.com/axieinfinity/public-smart-contracts',
      # here's ronin stuff. Not 100% on including it
      'https://github.com/axieinfinity/ronin-bridge-contracts',
      'https://github.com/axieinfinity/rns-contracts',
      'https://github.com/axieinfinity/ronin-dpos-contracts',
]),
]

PROJECT_CONFIGS_ALL_REPOS = [
  ProjectConfig(
    name="Dai",
    repo_urls=[
      "https://github.com/makerdao/sai.git",
      "https://github.com/makerdao/medianizer.git",
      "https://github.com/makerdao/pymaker.git",
      "https://github.com/makerdao/price-feed.git",
      "https://github.com/makerdao/median.git",
      "https://github.com/makerdao/proxy-registry.git",
      "https://github.com/makerdao/osm.git",
      "https://github.com/makerdao/vote-proxy.git",
      "https://github.com/makerdao/dss.git",
      "https://github.com/makerdao/dss-deploy.git",
      "https://github.com/makerdao/symbolic-voting.git",
      "https://github.com/makerdao/multicall.git",
      "https://github.com/makerdao/mcd-cdp-handler.git",
      "https://github.com/makerdao/dss-proxy-actions.git",
      "https://github.com/makerdao/scd-mcd-migration.git",
      "https://github.com/makerdao/dss-cdp-manager.git",
      "https://github.com/makerdao/developerguides.git",
      "https://github.com/makerdao/nft-adapter.git",
      "https://github.com/makerdao/token-faucet.git",
      "https://github.com/makerdao/testchain-medians.git",
      "https://github.com/makerdao/dss-deploy-pause-proxy-actions.git",
      "https://github.com/makerdao/esm.git",
      "https://github.com/makerdao/mkr-mom.git",
      "https://github.com/makerdao/mkr-authority.git",
      "https://github.com/makerdao/mkr-mcd-spec.git",
      "https://github.com/makerdao/savings-dai.git",
      "https://github.com/makerdao/spells-mainnet.git",
      "https://github.com/makerdao/megapoker.git",
      "https://github.com/makerdao/go-ethereum.git",
      "https://github.com/makerdao/dss-interfaces.git",
      "https://github.com/makerdao/osm-mom.git",
      "https://github.com/makerdao/keg.git",
      "https://github.com/makerdao/dsr-manager.git",
      "https://github.com/makerdao/dss-darkspell.git",
      "https://github.com/makerdao/mkr-mcd-spec-sol-tests.git",
      "https://github.com/makerdao/dss-gov.git",
      "https://github.com/makerdao/dss-auto-line.git",
      "https://github.com/makerdao/flipper-mom.git",
      "https://github.com/makerdao/sai-cagefree.git",
      "https://github.com/makerdao/dss-exigency.git",
      "https://github.com/makerdao/ilk-registry.git",
      "https://github.com/makerdao/ds-proxy.git",
      "https://github.com/makerdao/spells.git",
      "https://github.com/makerdao/spells-kovan.git",
      "https://github.com/makerdao/ds-pause.git",
      "https://github.com/makerdao/ds-chief.git",
      "https://github.com/makerdao/drizzle.git",
      "https://github.com/makerdao/dss-cat-overflow.git",
      "https://github.com/makerdao/dss-flash.git",
      "https://github.com/makerdao/dss-chain-log.git",
      "https://github.com/makerdao/exchange-callees.git",
      "https://github.com/makerdao/fib.git",
      "https://github.com/makerdao/univ2-lp-oracle.git",
      "https://github.com/makerdao/dss-exec-lib.git",
      "https://github.com/makerdao/dss-gem-joins.git",
      "https://github.com/makerdao/deployed-collateral-contracts.git",
      "https://github.com/makerdao/dss-lerp.git",
      "https://github.com/makerdao/dss-vest.git",
      "https://github.com/makerdao/clipper-mom.git",
      "https://github.com/makerdao/optimism-dai-bridge.git",
      "https://github.com/makerdao/MIP21-RWA-Example.git",
      "https://github.com/makerdao/dss-direct-deposit.git",
      "https://github.com/makerdao/mips-best-practices.git",
      "https://github.com/makerdao/vote-delegate.git",
      "https://github.com/makerdao/dss-crop-join.git",
      "https://github.com/makerdao/arbitrum-dai-bridge.git",
      "https://github.com/makerdao/ds-weth.git",
      "https://github.com/makerdao/univ3-lp-oracle.git",
      "https://github.com/makerdao/dss-charter.git",
      "https://github.com/makerdao/proxy-manager-clipper.git",
      "https://github.com/makerdao/spells-goerli.git",
      "https://github.com/makerdao/dss-psm.git",
      "https://github.com/makerdao/starknet-dai-bridge.git",
      "https://github.com/makerdao/JoinFab.git",
      "https://github.com/makerdao/curve-lp-oracle.git",
      "https://github.com/makerdao/dss-simulation-scripts.git",
      "https://github.com/makerdao/dss-teleport.git",
      "https://github.com/makerdao/dss-cron.git",
      "https://github.com/makerdao/dss-proxy-actions-steth.git",
      "https://github.com/makerdao/wormhole-integration-tests.git",
      "https://github.com/makerdao/dss-test.git",
      "https://github.com/makerdao/dss-proxy.git",
      "https://github.com/makerdao/dss-cdp-registry.git",
      "https://github.com/makerdao/dss-kiln.git",
      "https://github.com/makerdao/dss-gate.git",
      "https://github.com/makerdao/flash-killer.git",
      "https://github.com/makerdao/xdomain.git",
      "https://github.com/makerdao/xdomain-dss.git",
      "https://github.com/makerdao/rwa-toolkit.git",
      "https://github.com/makerdao/dss-onboard-ilk-helper.git",
      "https://github.com/makerdao/dss-gem-joins-integration-tests.git",
      "https://github.com/makerdao/sdai.git",
      "https://github.com/makerdao/protego.git",
      "https://github.com/makerdao/starknet-dss-bridge-tests.git",
      "https://github.com/makerdao/line-mom.git",
      "https://github.com/makerdao/endgame-toolkit.git",
      "https://github.com/makerdao/dss-flappers.git",
      "https://github.com/makerdao/token-tests.git",
      "https://github.com/makerdao/dss-allocator.git",
      "https://github.com/makerdao/dss-conduits.git",
    ],
  ),

  ProjectConfig(
    name="Tether USDt",
    repo_urls=[
      "https://github.com/tethercoin/dex-contracts.git",
      "https://github.com/tethercoin/dollar.git",
      "https://github.com/tethercoin/defidollar-core.git",
      "https://github.com/tethercoin/stablecoin-fun.git",
      "https://github.com/tethercoin/columbianpesogaslesspeg.git",
      "https://github.com/tethercoin/USDT.git",
      "https://github.com/tethercoin/digix-dao.git",
      "https://github.com/tethercoin/USDC.git",
      "https://github.com/tethercoin/GUH.git",
      "https://github.com/tethercoin/hedera-stable-coin-solidity-ethereum.git",
      "https://github.com/tethercoin/tethertoken.sol.git",
      "https://github.com/tethercoin/usdp-contracts.git",
      "https://github.com/tethercoin/busd-contract.git",
      "https://github.com/tethercoin/paxos-gold-contract.git",
      "https://github.com/tethercoin/bitcoin-token-smart-contracts.git",
      "https://github.com/tethercoin/dss-makerdai.git",
      "https://github.com/tethercoin/synthetix.git",
      "https://github.com/tethercoin/contracts-pre22-truefi.git",
      "https://github.com/tethercoin/ds-weth.git",
      "https://github.com/tethercoin/dss-deploy.git",
      "https://github.com/tethercoin/Anti-Gravity-Bridge.git",
      "https://github.com/tethercoin/BUSD.git",
      "https://github.com/tethercoin/PAXGOLD.git",
      "https://github.com/tethercoin/augur_foundry.git",
      "https://github.com/tethercoin/defi-Vault.git",
      "https://github.com/tethercoin/wrappedEth.git",
      "https://github.com/tethercoin/wusd-contracts.git",
      "https://github.com/tethercoin/dss-dai-stablecoin-system.git",
      "https://github.com/tethercoin/Acala.git",
      "https://github.com/tethercoin/gateway.git",
      "https://github.com/tethercoin/USM.git",
      "https://github.com/tethercoin/alpaca-stablecoin.git",
      "https://github.com/tethercoin/dss-interfaces.git",
      "https://github.com/tethercoin/gemini-dollar.git",
      "https://github.com/tethercoin/foundry-defi-stablecoin-f23.git",
    ],
  ),

  ProjectConfig(
    name="Osmosis",
    repo_urls=[
      "https://github.com/osmosis-labs/wormhole.git",
      "https://github.com/osmosis-labs/cosmos-gravity-bridge.git",
      "https://github.com/osmosis-labs/DefiLlama-Adapters.git",
    ],
  ),

  ProjectConfig(
    name="Ethereum Name Service",
    repo_urls=[
      "https://github.com/ensdomains/ens.git",
      "https://github.com/ensdomains/dnssec-oracle.git",
      "https://github.com/ensdomains/solsha1.git",
      "https://github.com/ensdomains/subdomain-registrar.git",
      "https://github.com/ensdomains/dnsregistrar.git",
      "https://github.com/ensdomains/blacklist.git",
      "https://github.com/ensdomains/court.git",
      "https://github.com/ensdomains/punycode.git",
      "https://github.com/ensdomains/buffer.git",
      "https://github.com/ensdomains/ethregistrar.git",
      "https://github.com/ensdomains/CurveArithmetics.git",
      "https://github.com/ensdomains/resolvers.git",
      "https://github.com/ensdomains/root.git",
      "https://github.com/ensdomains/optimistic-dnssec.git",
      "https://github.com/ensdomains/auction.git",
      "https://github.com/ensdomains/hackathon-registrar.git",
      "https://github.com/ensdomains/l2gateway-demo.git",
      "https://github.com/ensdomains/ens-archived-contracts.git",
      "https://github.com/ensdomains/name-wrapper.git",
      "https://github.com/ensdomains/dnssecoraclejs.git",
      "https://github.com/ensdomains/reverse-records.git",
      "https://github.com/ensdomains/tldclaims.git",
      "https://github.com/ensdomains/ens-contracts.git",
      "https://github.com/ensdomains/graph-node.git",
      "https://github.com/ensdomains/governance-contracts.git",
      "https://github.com/ensdomains/offchain-resolver.git",
      "https://github.com/ensdomains/op-resolver.git",
      "https://github.com/ensdomains/arbitrum-resolver.git",
      "https://github.com/ensdomains/arb-resolver.git",
      "https://github.com/ensdomains/ccip-tools.git",
      "https://github.com/ensdomains/gas-estimate-worker.git",
      "https://github.com/ensdomains/context-resolver.git",
      "https://github.com/ensdomains/evmgateway.git",
    ],
  ),

  ProjectConfig(
    name="Kava",
    repo_urls=[
      "https://github.com/Kava-Labs/kava.git",
      "https://github.com/Kava-Labs/dss.git",
      "https://github.com/Kava-Labs/kvtool.git",
      "https://github.com/Kava-Labs/kava-bridge.git",
      "https://github.com/Kava-Labs/blockscout.git",
      "https://github.com/Kava-Labs/ethermint.git",
      "https://github.com/Kava-Labs/hardhat-boilerplate.git",
      "https://github.com/Kava-Labs/kava-blockscout-build.git",
      "https://github.com/Kava-Labs/go-ethereum.git",
    ],
  ),

  ProjectConfig(
    name="Toncoin",
    repo_urls=[
      "https://github.com/ton-blockchain/bridge-solidity.git",
      "https://github.com/ton-blockchain/token-bridge-solidity.git",
      "https://github.com/ton-blockchain/ton-trustless-bridge-evm-contracts.git",
    ],
  ),

  ProjectConfig(
    name="Render",
    repo_urls=[
    ],
  ),

  ProjectConfig(
    name="Curve DAO Token",
    repo_urls=[
      "https://github.com/curvefi/curve-contract.git",
      "https://github.com/curvefi/curve-dao-contracts.git",
      "https://github.com/curvefi/curve-aragon-voting.git",
      "https://github.com/curvefi/curve-ren-adapter.git",
      "https://github.com/curvefi/unipool-fork.git",
      "https://github.com/curvefi/multi-rewards.git",
      "https://github.com/curvefi/curve-factory.git",
      "https://github.com/curvefi/brownie-tutorial.git",
      "https://github.com/curvefi/curve-xchain-factory.git",
      "https://github.com/curvefi/curve-merkle-oracle.git",
      "https://github.com/curvefi/tricrypto-ng.git",
      "https://github.com/curvefi/curve-xdao.git",
    ],
  ),

  # ProjectConfig(
  #   name="Maker",
  #   repo_urls=[
  #     "https://github.com/makerdao/sai.git",
  #     "https://github.com/makerdao/medianizer.git",
  #     "https://github.com/makerdao/pymaker.git",
  #     "https://github.com/makerdao/price-feed.git",
  #     "https://github.com/makerdao/median.git",
  #     "https://github.com/makerdao/proxy-registry.git",
  #     "https://github.com/makerdao/osm.git",
  #     "https://github.com/makerdao/vote-proxy.git",
  #     "https://github.com/makerdao/dss.git",
  #     "https://github.com/makerdao/dss-deploy.git",
  #     "https://github.com/makerdao/symbolic-voting.git",
  #     "https://github.com/makerdao/multicall.git",
  #     "https://github.com/makerdao/mcd-cdp-handler.git",
  #     "https://github.com/makerdao/dss-proxy-actions.git",
  #     "https://github.com/makerdao/scd-mcd-migration.git",
  #     "https://github.com/makerdao/dss-cdp-manager.git",
  #     "https://github.com/makerdao/developerguides.git",
  #     "https://github.com/makerdao/nft-adapter.git",
  #     "https://github.com/makerdao/token-faucet.git",
  #     "https://github.com/makerdao/testchain-medians.git",
  #     "https://github.com/makerdao/dss-deploy-pause-proxy-actions.git",
  #     "https://github.com/makerdao/esm.git",
  #     "https://github.com/makerdao/mkr-mom.git",
  #     "https://github.com/makerdao/mkr-authority.git",
  #     "https://github.com/makerdao/mkr-mcd-spec.git",
  #     "https://github.com/makerdao/savings-dai.git",
  #     "https://github.com/makerdao/spells-mainnet.git",
  #     "https://github.com/makerdao/megapoker.git",
  #     "https://github.com/makerdao/go-ethereum.git",
  #     "https://github.com/makerdao/dss-interfaces.git",
  #     "https://github.com/makerdao/osm-mom.git",
  #     "https://github.com/makerdao/keg.git",
  #     "https://github.com/makerdao/dsr-manager.git",
  #     "https://github.com/makerdao/dss-darkspell.git",
  #     "https://github.com/makerdao/mkr-mcd-spec-sol-tests.git",
  #     "https://github.com/makerdao/dss-gov.git",
  #     "https://github.com/makerdao/dss-auto-line.git",
  #     "https://github.com/makerdao/flipper-mom.git",
  #     "https://github.com/makerdao/sai-cagefree.git",
  #     "https://github.com/makerdao/dss-exigency.git",
  #     "https://github.com/makerdao/ilk-registry.git",
  #     "https://github.com/makerdao/ds-proxy.git",
  #     "https://github.com/makerdao/spells.git",
  #     "https://github.com/makerdao/spells-kovan.git",
  #     "https://github.com/makerdao/ds-pause.git",
  #     "https://github.com/makerdao/ds-chief.git",
  #     "https://github.com/makerdao/drizzle.git",
  #     "https://github.com/makerdao/dss-cat-overflow.git",
  #     "https://github.com/makerdao/dss-flash.git",
  #     "https://github.com/makerdao/dss-chain-log.git",
  #     "https://github.com/makerdao/exchange-callees.git",
  #     "https://github.com/makerdao/fib.git",
  #     "https://github.com/makerdao/univ2-lp-oracle.git",
  #     "https://github.com/makerdao/dss-exec-lib.git",
  #     "https://github.com/makerdao/dss-gem-joins.git",
  #     "https://github.com/makerdao/deployed-collateral-contracts.git",
  #     "https://github.com/makerdao/dss-lerp.git",
  #     "https://github.com/makerdao/dss-vest.git",
  #     "https://github.com/makerdao/clipper-mom.git",
  #     "https://github.com/makerdao/optimism-dai-bridge.git",
  #     "https://github.com/makerdao/MIP21-RWA-Example.git",
  #     "https://github.com/makerdao/dss-direct-deposit.git",
  #     "https://github.com/makerdao/mips-best-practices.git",
  #     "https://github.com/makerdao/vote-delegate.git",
  #     "https://github.com/makerdao/dss-crop-join.git",
  #     "https://github.com/makerdao/arbitrum-dai-bridge.git",
  #     "https://github.com/makerdao/ds-weth.git",
  #     "https://github.com/makerdao/univ3-lp-oracle.git",
  #     "https://github.com/makerdao/dss-charter.git",
  #     "https://github.com/makerdao/proxy-manager-clipper.git",
  #     "https://github.com/makerdao/spells-goerli.git",
  #     "https://github.com/makerdao/dss-psm.git",
  #     "https://github.com/makerdao/starknet-dai-bridge.git",
  #     "https://github.com/makerdao/JoinFab.git",
  #     "https://github.com/makerdao/curve-lp-oracle.git",
  #     "https://github.com/makerdao/dss-simulation-scripts.git",
  #     "https://github.com/makerdao/dss-teleport.git",
  #     "https://github.com/makerdao/dss-cron.git",
  #     "https://github.com/makerdao/dss-proxy-actions-steth.git",
  #     "https://github.com/makerdao/wormhole-integration-tests.git",
  #     "https://github.com/makerdao/dss-test.git",
  #     "https://github.com/makerdao/dss-proxy.git",
  #     "https://github.com/makerdao/dss-cdp-registry.git",
  #     "https://github.com/makerdao/dss-kiln.git",
  #     "https://github.com/makerdao/dss-gate.git",
  #     "https://github.com/makerdao/flash-killer.git",
  #     "https://github.com/makerdao/xdomain.git",
  #     "https://github.com/makerdao/xdomain-dss.git",
  #     "https://github.com/makerdao/rwa-toolkit.git",
  #     "https://github.com/makerdao/dss-onboard-ilk-helper.git",
  #     "https://github.com/makerdao/dss-gem-joins-integration-tests.git",
  #     "https://github.com/makerdao/sdai.git",
  #     "https://github.com/makerdao/protego.git",
  #     "https://github.com/makerdao/starknet-dss-bridge-tests.git",
  #     "https://github.com/makerdao/line-mom.git",
  #     "https://github.com/makerdao/endgame-toolkit.git",
  #     "https://github.com/makerdao/dss-flappers.git",
  #     "https://github.com/makerdao/token-tests.git",
  #     "https://github.com/makerdao/dss-allocator.git",
  #     "https://github.com/makerdao/dss-conduits.git",
  #   ],
  # ),

  ProjectConfig(
    name="USDC",
    repo_urls=[
      "https://github.com/circlefin/stablecoin-evm.git",
      "https://github.com/circlefin/verite.git",
      "https://github.com/circlefin/verite-minter-allowlist.git",
      "https://github.com/circlefin/perimeter-protocol.git",
      "https://github.com/circlefin/evm-cctp-contracts.git",
      "https://github.com/circlefin/recoverable-wrapper.git",
    ],
  ),

  ProjectConfig(
    name="Fantom",
    repo_urls=[
      "https://github.com/Fantom-foundation/go-lachesis.git",
      "https://github.com/Fantom-foundation/go-ethereum.git",
      "https://github.com/Fantom-foundation/fantom-sfc.git",
      "https://github.com/Fantom-foundation/data-hashing-authentication.git",
      "https://github.com/Fantom-foundation/fantom-govern.git",
      "https://github.com/Fantom-foundation/Fantom-Oracle-Pricefeed.git",
      "https://github.com/Fantom-foundation/Fantom-Fusd.git",
      "https://github.com/Fantom-foundation/Fantom-DeFi.git",
      "https://github.com/Fantom-foundation/Fantom-FMint.git",
      "https://github.com/Fantom-foundation/go-opera.git",
      "https://github.com/Fantom-foundation/Fantom-FLend.git",
      "https://github.com/Fantom-foundation/Fantom-wFTM.git",
      "https://github.com/Fantom-foundation/Fantom-Uniswap.git",
      "https://github.com/Fantom-foundation/lachesis-dag-tool.git",
      "https://github.com/Fantom-foundation/keep3r.network.git",
      "https://github.com/Fantom-foundation/opera-sfc.git",
      "https://github.com/Fantom-foundation/Fantom-Contract-Validation.git",
      "https://github.com/Fantom-foundation/Fantom-CrossChain-Bridge.git",
      "https://github.com/Fantom-foundation/crypto-fantom-game.git",
      "https://github.com/Fantom-foundation/Fantom-FLend-AAVE-v2.git",
      "https://github.com/Fantom-foundation/Fantom-Statheros.git",
      "https://github.com/Fantom-foundation/graph-node.git",
      "https://github.com/Fantom-foundation/gnosis_front.git",
      "https://github.com/Fantom-foundation/Artion-Contracts.git",
      "https://github.com/Fantom-foundation/fns-contracts.git",
      "https://github.com/Fantom-foundation/FtmStableCoin.git",
      "https://github.com/Fantom-foundation/FNS-SCs.git",
      "https://github.com/Fantom-foundation/fantom-web3j-sdk.git",
      "https://github.com/Fantom-foundation/example-deployment.git",
      "https://github.com/Fantom-foundation/go-opera-substate.git",
      "https://github.com/Fantom-foundation/go-ethereum-substate.git",
      "https://github.com/Fantom-foundation/Ledger-Hardhat-Deployment.git",
      "https://github.com/Fantom-foundation/unittestexample-hardhat.git",
      "https://github.com/Fantom-foundation/unittestexample-truffle.git",
      "https://github.com/Fantom-foundation/transparentproxy-hardhat.git",
      "https://github.com/Fantom-foundation/transparentproxy-truffle.git",
      "https://github.com/Fantom-foundation/transparentproxy2-hardhat.git",
      "https://github.com/Fantom-foundation/qewa.git",
      "https://github.com/Fantom-foundation/transparentproxy2-truffle.git",
      "https://github.com/Fantom-foundation/diamondproxy-hardhat.git",
      "https://github.com/Fantom-foundation/diamondproxy-truffle.git",
      "https://github.com/Fantom-foundation/go-lachesis-substate.git",
    ],
  ),

  ProjectConfig(
    name="Quant",
    repo_urls=[
    ],
  ),

  ProjectConfig(
    name="Fetch.ai",
    repo_urls=[
      "https://github.com/fetchai/agents-aea.git",
      "https://github.com/fetchai/staking-contract.git",
      "https://github.com/fetchai/ledger-staking-contract.git",
      "https://github.com/fetchai/mettalex-market-maker.git",
      "https://github.com/fetchai/fetch-ethereum-bridge-v1.git",
      "https://github.com/fetchai/safe-contracts.git",
      "https://github.com/fetchai/mobix-token.git",
    ],
  ),

  ProjectConfig(
    name="Chiliz",
    repo_urls=[
      "https://github.com/chiliz-chain/v2.git",
      "https://github.com/chiliz-chain/v2-genesis-config.git",
    ],
  ),

  ProjectConfig(
    name="PancakeSwap",
    repo_urls=[
      "https://github.com/pancakeswap/pancake-farm.git",
      "https://github.com/pancakeswap/pancake-swap-core.git",
      "https://github.com/pancakeswap/pancake-swap-periphery.git",
      "https://github.com/pancakeswap/pancake-swap-lib.git",
      "https://github.com/pancakeswap/lottery-contract.git",
      "https://github.com/pancakeswap/initial-farm-offering.git",
      "https://github.com/pancakeswap/pancake-smart-contracts.git",
      "https://github.com/pancakeswap/pancake-v3-contracts.git",
      "https://github.com/pancakeswap/permit2.git",
    ],
  ),

  ProjectConfig(
    name="KuCoin Token",
    repo_urls=[
    ],
  ),

  ProjectConfig(
    name="WOO",
    repo_urls=[
      "https://github.com/woonetwork/woo_token.git",
      "https://github.com/woonetwork/woofi_swap_smart_contracts.git",
      "https://github.com/woonetwork/DefiLlama-Adapters.git",
      "https://github.com/woonetwork/WooPoolV2.git",
      "https://github.com/woonetwork/WooStakingV2.git",
    ],
  ),

  ProjectConfig(
    name="Flow",
    repo_urls=[
      "https://github.com/onflow/flow-evm-bridge.git",
      "https://github.com/onflow/go-ethereum.git",
    ],
  ),

  ProjectConfig(
    name="Shiba Inu",
    repo_urls=[
      "https://github.com/shibaswaparmy/bor.git",
      "https://github.com/shibaswaparmy/contracts.git",
      "https://github.com/shibaswaparmy/genesis-contracts.git",
      "https://github.com/shibaswaparmy/pos-portal.git",
      "https://github.com/shibaswaparmy/chainhammer.git",
      "https://github.com/shibaswaparmy/fx-portal.git",
    ],
  ),

  ProjectConfig(
    name="The Graph",
    repo_urls=[
      "https://github.com/graphprotocol/graph-node.git",
      "https://github.com/graphprotocol/aragon-apps.git",
      "https://github.com/graphprotocol/ethabi.git",
      "https://github.com/graphprotocol/contracts.git",
      "https://github.com/graphprotocol/example-subgraph.git",
      "https://github.com/graphprotocol/everest.git",
      "https://github.com/graphprotocol/token-distribution.git",
      "https://github.com/graphprotocol/block-oracle.git",
      "https://github.com/graphprotocol/hardhat-graph-demo.git",
      "https://github.com/graphprotocol/example-subgraphs.git",
      "https://github.com/graphprotocol/erigon.git",
    ],
  ),

  ProjectConfig(
    name="Cronos",
    repo_urls=[
      "https://github.com/crypto-org-chain/cronos-smart-contract-example.git",
      "https://github.com/crypto-org-chain/ethermint.git",
      "https://github.com/crypto-org-chain/cronos-blockscout.git",
      "https://github.com/crypto-org-chain/cronos.git",
      "https://github.com/crypto-org-chain/gravity-bridge.git",
      "https://github.com/crypto-org-chain/go-ethereum.git",
      "https://github.com/crypto-org-chain/cronos-moralis-hackathon.git",
    ],
  ),

  ProjectConfig(
    name="Oasis Network",
    repo_urls=[
      "https://github.com/oasisprotocol/oasis-sdk.git",
      "https://github.com/oasisprotocol/web3-tests.git",
      "https://github.com/oasisprotocol/emerald-blockscout.git",
      "https://github.com/oasisprotocol/emerald-contracts.git",
      "https://github.com/oasisprotocol/nexus.git",
      "https://github.com/oasisprotocol/sapphire-paratime.git",
      "https://github.com/oasisprotocol/opengsn.git",
      "https://github.com/oasisprotocol/demo-voting.git",
      "https://github.com/oasisprotocol/demo-authzn.git",
      "https://github.com/oasisprotocol/demo-starter.git",
      "https://github.com/oasisprotocol/demo-oasisswag.git",
      "https://github.com/oasisprotocol/demo-oasisriddle.git",
      "https://github.com/oasisprotocol/demo-opl-secret-ballot.git",
      "https://github.com/oasisprotocol/demo-e2eproxy.git",
    ],
  ),

  ProjectConfig(
    name="Frax Share",
    repo_urls=[
      "https://github.com/FraxFinance/frax-solidity.git",
      "https://github.com/FraxFinance/frax-oracle-old.git",
      "https://github.com/FraxFinance/chaindata.git",
      "https://github.com/FraxFinance/protocol-v2.git",
      "https://github.com/FraxFinance/avalanche-bridge-resources.git",
      "https://github.com/FraxFinance/aave-asset-listing.git",
      "https://github.com/FraxFinance/compound-protocol.git",
      "https://github.com/FraxFinance/merkle-airdrop-starter.git",
      "https://github.com/FraxFinance/fraxlend.git",
      "https://github.com/FraxFinance/fraxlend-audit.git",
      "https://github.com/FraxFinance/frxETH-public.git",
      "https://github.com/FraxFinance/frax-vefpis.git",
      "https://github.com/FraxFinance/Foundry-Vyper.git",
      "https://github.com/FraxFinance/ERC4626.git",
      "https://github.com/FraxFinance/YieldSpaceAMO.git",
      "https://github.com/FraxFinance/frax-standard-solidity.git",
      "https://github.com/FraxFinance/frax-governance.git",
      "https://github.com/FraxFinance/frax-template.git",
      "https://github.com/FraxFinance/uni-v3-manipulation-simulator.git",
      "https://github.com/FraxFinance/staked-frax-erc4626.git",
      "https://github.com/FraxFinance/frax-bonds.git",
      "https://github.com/FraxFinance/frax-ether-redemption-queue.git",
      "https://github.com/FraxFinance/frax-oracles.git",
    ],
  ),

  ProjectConfig(
    name="Mantle",
    repo_urls=[
      "https://github.com/mantlenetworkio/mantle.git",
      "https://github.com/mantlenetworkio/mantle-erc20-bridge.git",
      "https://github.com/mantlenetworkio/mantle-tutorial.git",
      "https://github.com/mantlenetworkio/blockscout.git",
      "https://github.com/mantlenetworkio/specular.git",
      "https://github.com/mantlenetworkio/erigon.git",
      "https://github.com/mantlenetworkio/blockscout-rs.git",
      # # repos below are broken. I suspect a missing submodule.
      # "https://github.com/mantlenetworkio/mantle-token-contracts.git",
      # "https://github.com/mantlenetworkio/mantle-example-subgraph.git",
      # "https://github.com/mantlenetworkio/mantle-v2.git",
      # "https://github.com/mantlenetworkio/op-geth.git",
      # "https://github.com/mantlenetworkio/governance-crosschain-bridges.git",
      # "https://github.com/mantlenetworkio/lido-l2.git", 
    ],
  ),

  ProjectConfig(
    name="Rocket Pool",
    repo_urls=[
      "https://github.com/rocket-pool/rocketpool.git",
      "https://github.com/rocket-pool/rocketpool-beta-claim.git",
      "https://github.com/rocket-pool/eth2.0-specs.git",
      "https://github.com/rocket-pool/nethermind.git",
      "https://github.com/rocket-pool/rocketpool-ovm-oracle.git",
      "https://github.com/rocket-pool/rocketpool-router.git",
      "https://github.com/rocket-pool/rocketpool-arbitrum-oracle.git",
      "https://github.com/rocket-pool/rocketpool-polygon-oracle.git",
      "https://github.com/rocket-pool/rocketpool-zksync-oracle.git",
      "https://github.com/rocket-pool/compound-comet.git",
      "https://github.com/rocket-pool/rocketpool-scroll-oracle.git",
    ],
  ),

  ProjectConfig(
    name="Lido DAO",
    repo_urls=[
      "https://github.com/lidofinance/lido-dao.git",
      "https://github.com/lidofinance/lido-retro-airdrop.git",
      "https://github.com/lidofinance/staking-rewards-manager.git",
      "https://github.com/lidofinance/maker-integration.git",
      "https://github.com/lidofinance/curve-merkle-oracle.git",
      "https://github.com/lidofinance/scripts.git",
      "https://github.com/lidofinance/anchor-collateral-steth.git",
      "https://github.com/lidofinance/steth-price-feed.git",
      "https://github.com/lidofinance/aragon-apps.git",
      "https://github.com/lidofinance/rayonism-mev-hackathon.git",
      "https://github.com/lidofinance/withdrawals-manager-stub.git",
      "https://github.com/lidofinance/easy-track.git",
      "https://github.com/lidofinance/protocol-mock.git",
      "https://github.com/lidofinance/1inch-rewards-manager.git",
      "https://github.com/lidofinance/staking-rewards-sushi.git",
      "https://github.com/lidofinance/rewards-managers.git",
      "https://github.com/lidofinance/wsteth-eth-price-feed.git",
      "https://github.com/lidofinance/aave-protocol-v2.git",
      "https://github.com/lidofinance/aave-asteth-incentives-controller.git",
      "https://github.com/lidofinance/contract-helpers.git",
      "https://github.com/lidofinance/aave-asteth-deployment.git",
      "https://github.com/lidofinance/aave-asset-listing.git",
      "https://github.com/lidofinance/uni-v3-liquidity-provider.git",
      "https://github.com/lidofinance/cross-chain-token-relay.git",
      "https://github.com/lidofinance/jumpgates.git",
      "https://github.com/lidofinance/lido-l2.git",
      "https://github.com/lidofinance/avalanche-contracts.git",
      "https://github.com/lidofinance/governance-crosschain-bridges.git",
      "https://github.com/lidofinance/lido-otc-seller.git",
      "https://github.com/lidofinance/insurance-fund.git",
      "https://github.com/lidofinance/aave-v3-core.git",
      "https://github.com/lidofinance/polygon-contracts.git",
      "https://github.com/lidofinance/stonks.git",
      "https://github.com/lidofinance/dual-governance.git",
      "https://github.com/lidofinance/linea-contracts-fix.git",
      "https://github.com/lidofinance/linea-contracts.git",
      "https://github.com/lidofinance/comet.git",
    ],
  ),

  ProjectConfig(
    name="Chainlink",
    repo_urls=[
      "https://github.com/smartcontractkit/chainlink-ruby.git",
      "https://github.com/smartcontractkit/LinkToken.git",
      "https://github.com/smartcontractkit/chainlink.git",
      "https://github.com/smartcontractkit/solidity-cborutils.git",
      "https://github.com/smartcontractkit/buffer.git",
      "https://github.com/smartcontractkit/mixicles.git",
      "https://github.com/smartcontractkit/chainlink-polkadot.git",
      "https://github.com/smartcontractkit/0x-monorepo.git",
      "https://github.com/smartcontractkit/truffle-starter-kit.git",
      "https://github.com/smartcontractkit/MultiSigWallet.git",
      "https://github.com/smartcontractkit/chainlink-RSK.git",
      "https://github.com/smartcontractkit/link-token-sidechain-evm.git",
      "https://github.com/smartcontractkit/libocr.git",
      "https://github.com/smartcontractkit/ens-resolver.git",
      "https://github.com/smartcontractkit/chainlink-mix.git",
      "https://github.com/smartcontractkit/go-ethereum.git",
      "https://github.com/smartcontractkit/compound-protocol.git",
      "https://github.com/smartcontractkit/feed-registry.git",
      "https://github.com/smartcontractkit/hardhat-starter-kit.git",
      "https://github.com/smartcontractkit/documentation.git",
      "https://github.com/smartcontractkit/chainlink-brownie-contracts.git",
      "https://github.com/smartcontractkit/open-oracle.git",
      "https://github.com/smartcontractkit/upkeep-contracts.git",
      "https://github.com/smartcontractkit/feed-registry-example.git",
      "https://github.com/smartcontractkit/keeper.git",
      "https://github.com/smartcontractkit/ccip-read.git",
      "https://github.com/smartcontractkit/bitcoin-token-smart-contracts.git",
      "https://github.com/smartcontractkit/chainlink-fullstack.git",
      "https://github.com/smartcontractkit/aave-protocol-v2.git",
      "https://github.com/smartcontractkit/ethereum-datetime.git",
      "https://github.com/smartcontractkit/solidity-stringutils.git",
      "https://github.com/smartcontractkit/trusttoken-smart-contracts.git",
      "https://github.com/smartcontractkit/dapptools-starter-kit.git",
      "https://github.com/smartcontractkit/smart-contract-examples.git",
      "https://github.com/smartcontractkit/foundry-starter-kit-old.git",
      "https://github.com/smartcontractkit/defi-minimal.git",
      "https://github.com/smartcontractkit/chainlink-automation-templates.git",
      "https://github.com/smartcontractkit/chainlink-starknet.git",
      "https://github.com/smartcontractkit/starkgate-contracts.git",
      "https://github.com/smartcontractkit/foundry-starter-kit.git",
      "https://github.com/smartcontractkit/por-demo-contracts.git",
      "https://github.com/smartcontractkit/huff-starter-kit.git",
      "https://github.com/smartcontractkit/vrf-experiences.git",
      "https://github.com/smartcontractkit/chainlink-solhint-rules-example.git",
      "https://github.com/smartcontractkit/chainlink-in-web2-fh22.git",
      "https://github.com/smartcontractkit/DEVREL-collaborative-nft-tutorial.git",
      "https://github.com/smartcontractkit/staking-v0.1.git",
      "https://github.com/smartcontractkit/hardhat-chainlink.git",
      "https://github.com/smartcontractkit/functions-hardhat-starter-kit.git",
      "https://github.com/smartcontractkit/foundry-chainlink-toolkit.git",
      "https://github.com/smartcontractkit/devrel-merkle-tree.git",
      "https://github.com/smartcontractkit/hardhat-chainlink-example.git",
      "https://github.com/smartcontractkit/functions-twilio-spotify.git",
      "https://github.com/smartcontractkit/devrel-testing-with-hardhat.git",
      "https://github.com/smartcontractkit/functions-google-bigquery.git",
      "https://github.com/smartcontractkit/functions-insurance.git",
      "https://github.com/smartcontractkit/functions-aws-currency-data.git",
      "https://github.com/smartcontractkit/functions-meta-giveaway.git",
      "https://github.com/smartcontractkit/ccip-starter-kit-foundry.git",
      "https://github.com/smartcontractkit/quickstarts-lootbox.git",
      "https://github.com/smartcontractkit/quickstarts-mysterybox.git",
      "https://github.com/smartcontractkit/timelock-worker.git",
      "https://github.com/smartcontractkit/chainlink-functions-demo-app.git",
      "https://github.com/smartcontractkit/ccip-tic-tac-toe.git",
      "https://github.com/smartcontractkit/ccip-starter-kit-hardhat.git",
      "https://github.com/smartcontractkit/ccip-cross-chain-name-service.git",
      "https://github.com/smartcontractkit/ccip-liquidation-protector.git",
      "https://github.com/smartcontractkit/ccip-cross-chain-nft.git",
      "https://github.com/smartcontractkit/ccip-defi-lending.git",
      "https://github.com/smartcontractkit/functions-the-graph-uniswap.git",
      "https://github.com/smartcontractkit/quickstarts-giveaway.git",
      "https://github.com/smartcontractkit/ccip.git",
      "https://github.com/smartcontractkit/ccip-owner-contracts.git",
      "https://github.com/smartcontractkit/vrf-direct-funding-example.git",
      "https://github.com/smartcontractkit/functions-toolkit.git",
      "https://github.com/smartcontractkit/quickstarts-circuitbreaker.git",
      "https://github.com/smartcontractkit/quickstarts-vrf-balance-manager.git",
      "https://github.com/smartcontractkit/functions-bigquery-weather.git",
      "https://github.com/smartcontractkit/functions-toolkit-workshop.git",
      "https://github.com/smartcontractkit/functions-google-vertex-ai.git",
      "https://github.com/smartcontractkit/functions-lens-eventbrite.git",
      "https://github.com/smartcontractkit/functions-chainalysis.git",
      "https://github.com/smartcontractkit/functions-aws-iot-core.git",
      "https://github.com/smartcontractkit/prediction-game.git",
      "https://github.com/smartcontractkit/datastreams-demo.git",
      "https://github.com/smartcontractkit/functions-deepdive-constellation2023.git",
      "https://github.com/smartcontractkit/run-functions-dapp.git",
      "https://github.com/smartcontractkit/workshop-distributed-news.git",
      "https://github.com/smartcontractkit/datastreams-erc7412.git",
    ],
  ),

  ProjectConfig(
    name="Terra Classic",
    repo_urls=[
      "https://github.com/terra-money/shuttle.git",
      "https://github.com/terra-money/wormhole.git",
      "https://github.com/terra-money/protocol-v2.git",
      "https://github.com/terra-money/aave-asset-listing.git",
      "https://github.com/terra-money/incentives-controller.git",
    ],
  ),

  ProjectConfig(
    name="Immutable",
    repo_urls=[
      "https://github.com/immutable/imx-core-sdk-kotlin-jvm.git",
      "https://github.com/immutable/imx-core-sdk.git",
      "https://github.com/immutable/imx-core-sdk-golang.git",
      "https://github.com/immutable/contracts.git",
      "https://github.com/immutable/ts-immutable-sdk.git",
      "https://github.com/immutable/wallet-contracts.git",
      "https://github.com/immutable/seaport-core.git",
      "https://github.com/immutable/seaport.git",
      "https://github.com/immutable/sample-passport-unity-game.git",
      "https://github.com/immutable/axelar-docs.git",
    ],
  ),

  ProjectConfig(
    name="Axie Infinity",
    repo_urls=[
      "https://github.com/axieinfinity/ronin.git",
      "https://github.com/axieinfinity/ronin-smart-contracts.git",
      "https://github.com/axieinfinity/bridge-v2.git",
      "https://github.com/axieinfinity/ronin-dpos-contracts.git",
      "https://github.com/axieinfinity/contract-template.git",
      "https://github.com/axieinfinity/rns-contracts.git",
      "https://github.com/axieinfinity/foundry-deployment-kit.git",
      "https://github.com/axieinfinity/ronin-bridge-contracts.git",
    ],
  ),

  ProjectConfig(
    name="Synthetix",
    repo_urls=[
      "https://github.com/Synthetixio/synthetix.git",
      "https://github.com/Synthetixio/utility-contracts.git",
      "https://github.com/Synthetixio/Unipool.git",
      "https://github.com/Synthetixio/snx-grants-dao.git",
      "https://github.com/Synthetixio/buidler.git",
      "https://github.com/Synthetixio/spartan-council.git",
      "https://github.com/Synthetixio/synthetix-v3-labs.git",
      "https://github.com/Synthetixio/council-dilution.git",
      "https://github.com/Synthetixio/synthetix-v3.git",
      "https://github.com/Synthetixio/snx-grants-dao-v2.git",
      "https://github.com/Synthetixio/synthetix-grants.git",
      "https://github.com/Synthetixio/susd-incentives-aave.git",
      "https://github.com/Synthetixio/futures-keepers.git",
      "https://github.com/Synthetixio/hardhat-interact.git",
      "https://github.com/Synthetixio/tokenvest.git",
      "https://github.com/Synthetixio/snx-v3-prototype.git",
      "https://github.com/Synthetixio/uniswap-v3-spot-twap-oracle.git",
      "https://github.com/Synthetixio/safe-synthetix-module.git",
      "https://github.com/Synthetixio/synthetix-sandbox.git",
      "https://github.com/Synthetixio/v2x-legacy-migrations.git",
      # # Repos below don't work. I think they have missing submodules
      # "https://github.com/Synthetixio/v3-markets-prototype.git",
      # "https://github.com/Synthetixio/number-guessing-game.git",
      # "https://github.com/Synthetixio/bfp-market.git",
      # "https://github.com/Synthetixio/erc7412.git",
      # "https://github.com/Synthetixio/external-nodes.git",
      # "https://github.com/Synthetixio/trusted-multicall-forwarder.git",
      # "https://github.com/Synthetixio/erc7412-wormhole.git",
      # "https://github.com/Synthetixio/rewards-distributors.git",
      # "https://github.com/Synthetixio/example-rewards-distributor.git",
    ],
  ),

  ProjectConfig(
    name="The Sandbox",
    repo_urls=[
      "https://github.com/thesandboxgame/sandbox-smart-contracts-old.git",
      "https://github.com/thesandboxgame/sandbox-smart-contracts.git",
      "https://github.com/thesandboxgame/assetbug.git",
      "https://github.com/thesandboxgame/dappeteer.git",
    ],
  ),

  ProjectConfig(
    name="Uniswap",
    repo_urls=[
      "https://github.com/Uniswap/v2-core.git",
      "https://github.com/Uniswap/v2-periphery.git",
      "https://github.com/Uniswap/solidity-lib.git",
      "https://github.com/Uniswap/v3-core.git",
      "https://github.com/Uniswap/merkle-distributor.git",
      "https://github.com/Uniswap/liquidity-staker.git",
      "https://github.com/Uniswap/governance.git",
      "https://github.com/Uniswap/v3-periphery.git",
      "https://github.com/Uniswap/v3-staker.git",
      "https://github.com/Uniswap/v3-core-optimism.git",
      "https://github.com/Uniswap/v3-periphery-optimism.git",
      "https://github.com/Uniswap/swap-router-contracts.git",
      "https://github.com/Uniswap/polygon-bridge.git",
      "https://github.com/Uniswap/v4-core.git",
      "https://github.com/Uniswap/lp-action-contracts.git",
      "https://github.com/Uniswap/v4-periphery.git",
      "https://github.com/Uniswap/ethers-rs-mobile.git",
      "https://github.com/Uniswap/uniswap-first-contract-example.git",
      "https://github.com/Uniswap/UniswapX.git",
      "https://github.com/Uniswap/universal-router.git",
      "https://github.com/Uniswap/universal-router-sdk.git",
      "https://github.com/Uniswap/permit2.git",
      "https://github.com/Uniswap/permit2-sdk.git",
      "https://github.com/Uniswap/marketdepth-v3.git",
      "https://github.com/Uniswap/offchain-resolver.git",
      "https://github.com/Uniswap/view-quoter-v3.git",
      "https://github.com/Uniswap/relayer.git",
    ],
  ),

  ProjectConfig(
    name="Decentraland",
    repo_urls=[
      "https://github.com/decentraland/mana.git",
      "https://github.com/decentraland/land.git",
      "https://github.com/decentraland/erc721.git",
      "https://github.com/decentraland/marketplace-contracts.git",
      "https://github.com/decentraland/dappeteer.git",
      "https://github.com/decentraland/land-auction.git",
      "https://github.com/decentraland/aux-contracts.git",
      "https://github.com/decentraland/pass-through.git",
      "https://github.com/decentraland/avatars-contract.git",
      "https://github.com/decentraland/decentraland-claim-app.git",
      "https://github.com/decentraland/wearables-contracts.git",
      "https://github.com/decentraland/dao-apps.git",
      "https://github.com/decentraland/marketplace-adapter.git",
      "https://github.com/decentraland/vestings-builder.git",
      "https://github.com/decentraland/graph-node.git",
      "https://github.com/decentraland/dummy-token.git",
      "https://github.com/decentraland/MultiSigWallet.git",
      "https://github.com/decentraland/bid-contract.git",
      "https://github.com/decentraland/content-hash-tree.git",
      "https://github.com/decentraland/rentals-contract.git",
      "https://github.com/decentraland/common-contracts.git",
      "https://github.com/decentraland/checker-contract.git",
    ],
  ),

  ProjectConfig(
    name="Aave",
    repo_urls=[
      "https://github.com/aave/aave-js.git",
      "https://github.com/aave/aave-protocol.git",
      "https://github.com/aave/flashloan-box.git",
      "https://github.com/aave/aave-token.git",
      "https://github.com/aave/proto-governance.git",
      "https://github.com/aave/safety-module.git",
      "https://github.com/aave/genesis-migration.git",
      "https://github.com/aave/upgradeable-configurable-rights-pool.git",
      "https://github.com/aave/code-examples-protocol.git",
      "https://github.com/aave/protocol-v2.git",
      "https://github.com/aave/governance-v2.git",
      "https://github.com/aave/aave-token-v2.git",
      "https://github.com/aave/aave-stake-v2.git",
      "https://github.com/aave/aave-asset-listing.git",
      "https://github.com/aave/tests-protocol-v2-sigmaprime.git",
      "https://github.com/aave/price-aggregators.git",
      "https://github.com/aave/incentives-controller.git",
      "https://github.com/aave/governance-crosschain-bridges.git",
      "https://github.com/aave/aave-v3-core.git",
      "https://github.com/aave/aave-v3-periphery.git",
      "https://github.com/aave/arc-timelock.git",
      "https://github.com/aave/aave-sandbox.git",
      "https://github.com/aave/gho-core.git",
      "https://github.com/aave/v3-retroactive-funding.git",
      # # Below repos aren't working, I think bc deleted github submodules
      # "https://github.com/aave/Aave-Vault.git",
      # "https://github.com/aave/aave-v3-deploy.git",
      # "https://github.com/aave/gho-aip.git",
      # "https://github.com/aave/aave-address-book.git",
      # "https://github.com/aave/aave-proposals.git",
      # "https://github.com/aave/token-wrappers.git",
      # "https://github.com/aave/aave-proposals-aip.git",
      # "https://github.com/aave/aave-debt-swap.git",
      # "https://github.com/aave/aave-proposals-v3.git",
    ],
  ),

  ProjectConfig(
    name="Polygon",
    repo_urls=[
      "https://github.com/maticnetwork/contracts.git",
      "https://github.com/maticnetwork/tokenized-pos.git",
      "https://github.com/maticnetwork/testnet-token-contracts.git",
      "https://github.com/maticnetwork/pos-commit-poc.git",
      "https://github.com/maticnetwork/ethindia-workshop.git",
      "https://github.com/maticnetwork/predict.git",
      "https://github.com/maticnetwork/genesis-contracts.git",
      "https://github.com/maticnetwork/bor.git",
      "https://github.com/maticnetwork/pos-portal.git",
      "https://github.com/maticnetwork/Solidity-RLP.git",
      "https://github.com/maticnetwork/augur.git",
      "https://github.com/maticnetwork/governance-contracts.git",
      "https://github.com/maticnetwork/erigon.git",
      "https://github.com/maticnetwork/go-ethereum.git",
      "https://github.com/maticnetwork/eip-1559-burn.git",
      "https://github.com/maticnetwork/polygon-sdk.git",
      "https://github.com/maticnetwork/ethereumjs-monorepo.git",
      "https://github.com/maticnetwork/v3-monorepo.git",
      "https://github.com/maticnetwork/polygon-cli.git",
      "https://github.com/maticnetwork/mint-backend.git",
    ],
  ),
]
